import { useCallback, useEffect, useMemo, useState } from "react";
import { BookOpen, Download, ExternalLink, FileText, RefreshCw, Search, Tags } from "lucide-react";
import { apiGetLibraryBooks, type LibraryBook } from "@/lib/api-client";

export default function TessLibraryPage() {
  const [books, setBooks] = useState<LibraryBook[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { setBooks(await apiGetLibraryBooks()); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "La bibliothèque est indisponible."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => books.filter(book => `${book.title} ${book.author} ${book.description} ${book.category} ${book.tags}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [books, query]);

  return <main className="h-full overflow-y-auto bg-[var(--tess-bg)] px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[var(--tess-accent)]">T.E.S.S. · Ressources</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[var(--tess-ink)]">Bibliothèque</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--tess-muted)]">Retrouve les ressources publiées et les documents disponibles pour tes échanges avec TESS.</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-[var(--tess-line)] bg-white px-3 py-2 text-sm font-semibold text-[var(--tess-ink)] transition hover:bg-[var(--tess-mint)] disabled:opacity-50 dark:bg-white/[0.04]"><RefreshCw className={loading ? "h-4 w-4 animate-spin" : "h-4 w-4"} />Actualiser</button></header>
    <label className="mt-6 flex min-h-11 items-center gap-2 rounded-xl border border-[var(--tess-line)] bg-white px-3 dark:bg-white/[0.04]"><Search className="h-4 w-4 text-[var(--tess-muted)]" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Rechercher un titre, auteur ou sujet…" className="min-w-0 flex-1 bg-transparent text-sm text-[var(--tess-ink)] outline-none placeholder:text-[var(--tess-muted)]" /></label>
    {error && <div role="alert" className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-400/20 dark:bg-rose-500/10 dark:text-rose-200">{error}<button type="button" onClick={() => void load()} className="ml-3 font-semibold underline">Réessayer</button></div>}
    {loading && !books.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }, (_, i) => <div key={i} className="tess-hub-card h-64 animate-pulse rounded-2xl border" />)}</div> : visible.length ? <section aria-label="Ressources de la bibliothèque" className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map(book => <article key={book.id} className="tess-hub-card overflow-hidden rounded-2xl border transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex h-36 items-center justify-center bg-[var(--tess-mint)]/40">{book.cover_image ? <img src={book.cover_image} alt={`Couverture : ${book.title}`} className="h-full w-full object-cover" /> : <BookOpen className="h-10 w-10 text-[var(--tess-muted)]" />}</div><div className="p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="line-clamp-2 font-semibold text-[var(--tess-ink)]">{book.title}</h2><p className="mt-1 text-xs text-[var(--tess-muted)]">{book.author || "Auteur non précisé"}</p></div>{book.category && <span className="shrink-0 rounded-full bg-[var(--tess-mint)] px-2 py-1 text-[10px] font-semibold text-[var(--tess-ink)]">{book.category}</span>}</div>{book.description && <p className="mt-3 line-clamp-3 text-sm leading-5 text-[var(--tess-muted)]">{book.description}</p>}<div className="mt-4 flex flex-wrap gap-2 text-[10px] text-[var(--tess-muted)]">{book.resource_type && <span className="inline-flex items-center gap-1"><FileText className="h-3 w-3" />{book.resource_type}</span>}{book.language && <span>{book.language}</span>}{book.page_count > 0 && <span>{book.page_count} pages</span>}{book.tags && <span className="inline-flex items-center gap-1"><Tags className="h-3 w-3" />{book.tags}</span>}</div><div className="mt-4 flex gap-2">{(book.read_url || book.file_url) && <a href={book.read_url || book.file_url} target="_blank" rel="noreferrer" className="inline-flex min-h-9 flex-1 items-center justify-center gap-2 rounded-lg bg-slate-900 px-3 text-xs font-semibold text-white hover:bg-slate-700 dark:bg-white dark:text-slate-900"><ExternalLink className="h-3.5 w-3.5" />Ouvrir</a>}{book.download_url && <a href={book.download_url} target="_blank" rel="noreferrer" aria-label={`Télécharger ${book.title}`} className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-[var(--tess-line)] text-[var(--tess-ink)] hover:bg-[var(--tess-mint)]"><Download className="h-4 w-4" /></a>}</div></div></article>)}</section> : <div className="mt-6 rounded-2xl border border-dashed border-[var(--tess-line)] p-10 text-center"><BookOpen className="mx-auto h-8 w-8 text-[var(--tess-muted)]" /><h2 className="mt-3 font-semibold text-[var(--tess-ink)]">{query ? "Aucun résultat" : "La bibliothèque est vide"}</h2><p className="mt-1 text-sm text-[var(--tess-muted)]">{query ? "Essaie un autre titre ou sujet." : "Les ressources publiées apparaîtront ici."}</p></div>}
  </div></main>;
}
