import { useCallback, useEffect, useState } from "react";
import { KeyRound, RefreshCw, ShieldCheck, Wrench } from "lucide-react";
import { tessFetch, type TessTool } from "@/lib/tess-client";

export default function TessToolsPage() {
  const [tools, setTools] = useState<TessTool[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setTools(await tessFetch<TessTool[]>("/tools")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger le registre d’outils."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <main className="h-full overflow-y-auto bg-[var(--tess-bg)] px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[var(--tess-accent)]">T.E.S.S. · Capacités</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[var(--tess-ink)]">Tool Registry</h1><p className="mt-2 max-w-2xl text-sm text-[var(--tess-muted)]">Contrats déclarés par le runtime. Une capacité n’est utilisable qu’avec ses permissions et sa policy.</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-[var(--tess-line)] px-3 py-2 text-sm font-semibold text-[var(--tess-ink)] hover:bg-[var(--tess-mint)] disabled:opacity-50"><RefreshCw className={loading ? "h-4 w-4 animate-spin" : "h-4 w-4"} /> Actualiser</button></header>{error && <div role="alert" className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}<section className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{tools.map(tool => <article key={tool.tool_id} className="tess-hub-card rounded-2xl border p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--tess-mint)] text-[var(--tess-ink)]"><Wrench className="h-5 w-5" /></span><div className="min-w-0"><h2 className="truncate font-semibold text-[var(--tess-ink)]">{tool.name}</h2><p className="truncate font-mono text-[10px] text-[var(--tess-muted)]">{tool.tool_id}</p></div></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${tool.confirmation_required ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{tool.confirmation_required ? "Confirmation" : "Lecture directe"}</span></div><p className="mt-4 text-sm leading-6 text-[var(--tess-muted)]">{tool.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{tool.permissions.map(permission => <span key={permission} className="inline-flex items-center gap-1 rounded-md bg-[var(--tess-mint)] px-2 py-1 text-[10px] text-[var(--tess-ink)]"><KeyRound className="h-3 w-3" />{permission}</span>)}</div><div className="mt-4 flex items-center gap-2 text-[10px] text-[var(--tess-muted)]"><ShieldCheck className="h-3.5 w-3.5" /> Risque : {tool.risk_level} · Agents : {tool.agent_ids.length}</div></article>)}{!loading && !tools.length && <p className="col-span-full rounded-2xl border border-dashed border-[var(--tess-line)] px-4 py-10 text-center text-sm text-[var(--tess-muted)]">Le registre ne contient aucun outil.</p>}</section></div></main>;
}
