import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Check, CircleCheck, LockKeyhole, Play, RefreshCw, Shield, ShieldAlert, ShieldCheck, Square, X } from "lucide-react";
import { tessFetch } from "@/lib/tess-client";

type AutonomyStatus = { state?: string; reason?: string | null; lockdown?: boolean; active_tokens?: number; open_circuits?: unknown[] };
type Approval = { approval_id: string; mission_id?: string | null; step_id?: string | null; agent_id?: string | null; action?: string; risk_level?: string; reason?: string; status: string; requested_at?: string; decided_by?: string | null; decided_at?: string | null };
type ControlAction = "stop" | "resume" | "lockdown" | "release-lockdown";

export default function TessOperatorPage() {
  const [status, setStatus] = useState<AutonomyStatus | null>(null);
  const [approvals, setApprovals] = useState<Approval[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState("");
  const [pendingControl, setPendingControl] = useState<ControlAction | null>(null);
  const [controlReason, setControlReason] = useState("");
  const [pendingDecision, setPendingDecision] = useState<{ approval: Approval; approved: boolean } | null>(null);
  const [notice, setNotice] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const [runtime, pending] = await Promise.all([tessFetch<AutonomyStatus>("/autonomy/status"), tessFetch<Approval[]>("/autonomy/approvals")]); setStatus(runtime); setApprovals(pending); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Les informations opérateur ne sont pas accessibles."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const runControl = async () => {
    if (!pendingControl) return;
    setBusy(pendingControl); setError(""); setNotice("");
    try {
      const body = pendingControl === "stop" || pendingControl === "lockdown" ? { reason: controlReason.trim() } : undefined;
      setStatus(await tessFetch<AutonomyStatus>(`/autonomy/${pendingControl}`, { method: "POST", ...(body ? { body: JSON.stringify(body) } : {}) }));
      setNotice("La commande a été acceptée par le runtime."); setPendingControl(null); setControlReason("");
      const latest = await tessFetch<Approval[]>("/autonomy/approvals"); setApprovals(latest);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Commande refusée par le runtime."); }
    finally { setBusy(""); }
  };
  const decide = async () => {
    if (!pendingDecision) return;
    const { approval, approved } = pendingDecision;
    setBusy(approval.approval_id); setError(""); setNotice("");
    try {
      await tessFetch(`/autonomy/approvals/${encodeURIComponent(approval.approval_id)}`, { method: "POST", body: JSON.stringify({ approved }) });
      setNotice(approved ? "Approbation enregistrée." : "Demande rejetée."); setPendingDecision(null); await load();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "La décision n’a pas été enregistrée."); }
    finally { setBusy(""); }
  };
  const openApprovals = approvals.filter(item => ["PENDING", "WAITING_APPROVAL", "OPEN"].includes(item.status.toUpperCase()));
  const actionLabel: Record<ControlAction, string> = { stop: "Arrêter le runtime", resume: "Reprendre le runtime", lockdown: "Activer le verrouillage", "release-lockdown": "Lever le verrouillage et reprendre" };
  const requiresReason = pendingControl === "stop" || pendingControl === "lockdown";

  return <main className="h-full overflow-y-auto bg-[var(--tess-bg)] px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[var(--tess-accent)]">T.E.S.S. · Opérateur</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[var(--tess-ink)]">Contrôle et approbations</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--tess-muted)]">État du garde-fou d’autonomie et décisions en attente. Les actions sont soumises aux permissions du serveur.</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-[var(--tess-line)] bg-white px-3 py-2 text-sm font-semibold text-[var(--tess-ink)] transition hover:bg-[var(--tess-mint)] disabled:opacity-50 dark:bg-white/[0.04]"><RefreshCw className={loading ? "h-4 w-4 animate-spin" : "h-4 w-4"} />Actualiser</button></header>
    <div className="mt-5 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:border-amber-400/20 dark:bg-amber-400/[0.08] dark:text-amber-100"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><p>Les contrôles stop/lockdown ont un effet sur le runtime. Ils demandent une confirmation, et le serveur vérifie les permissions requises.</p></div>
    {error && <div role="alert" className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-400/20 dark:bg-rose-500/10 dark:text-rose-200">{error}</div>}{notice && <div role="status" className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-400/20 dark:bg-emerald-500/10 dark:text-emerald-200">{notice}</div>}
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="tess-hub-card rounded-2xl border p-4"><ShieldCheck className="h-5 w-5 text-emerald-600" /><p className="mt-3 text-xs text-[var(--tess-muted)]">Runtime</p><strong className="mt-1 block text-lg text-[var(--tess-ink)]">{status?.state || (loading ? "Chargement…" : "Indisponible")}</strong></article><article className="tess-hub-card rounded-2xl border p-4"><LockKeyhole className="h-5 w-5 text-[var(--tess-accent)]" /><p className="mt-3 text-xs text-[var(--tess-muted)]">Verrouillage</p><strong className="mt-1 block text-lg text-[var(--tess-ink)]">{status?.lockdown ? "Activé" : loading ? "…" : "Inactif"}</strong></article><article className="tess-hub-card rounded-2xl border p-4"><Shield className="h-5 w-5 text-blue-600" /><p className="mt-3 text-xs text-[var(--tess-muted)]">Jetons actifs</p><strong className="mt-1 block text-lg text-[var(--tess-ink)]">{status?.active_tokens ?? (loading ? "…" : "—")}</strong></article><article className="tess-hub-card rounded-2xl border p-4"><ShieldAlert className="h-5 w-5 text-amber-600" /><p className="mt-3 text-xs text-[var(--tess-muted)]">Approbations en attente</p><strong className="mt-1 block text-lg text-[var(--tess-ink)]">{openApprovals.length}</strong></article></section>
    <section className="mt-6 tess-hub-card rounded-2xl border p-5"><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-[var(--tess-accent)]" /><h2 className="font-semibold text-[var(--tess-ink)]">Contrôles du runtime</h2></div><div className="mt-4 flex flex-wrap gap-2">{([{ id: "stop", icon: Square }, { id: "resume", icon: Play }, { id: "lockdown", icon: LockKeyhole }, { id: "release-lockdown", icon: ShieldCheck }] as const).map(({ id, icon: Icon }) => <button key={id} type="button" onClick={() => { setPendingControl(id); setControlReason(""); setError(""); }} disabled={Boolean(busy) || loading} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--tess-line)] px-3 text-xs font-semibold text-[var(--tess-ink)] transition hover:bg-[var(--tess-mint)] disabled:opacity-50"><Icon className="h-3.5 w-3.5" />{actionLabel[id]}</button>)}</div>{status?.reason && <p className="mt-3 text-xs text-[var(--tess-muted)]">Motif du runtime : {status.reason}</p>}</section>
    <section className="mt-6"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold text-[var(--tess-ink)]">Demandes d’approbation</h2><p className="mt-1 text-xs text-[var(--tess-muted)]">Une décision est envoyée au runtime et peut être irréversible.</p></div><span className="rounded-full bg-[var(--tess-mint)] px-2.5 py-1 text-xs font-semibold text-[var(--tess-ink)]">{openApprovals.length} en attente</span></div>{openApprovals.length ? <div className="space-y-3">{openApprovals.map(item => <article key={item.approval_id} className="tess-hub-card rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-[var(--tess-ink)]">{item.action || item.step_id || "Action à valider"}</h3><p className="mt-1 text-xs text-[var(--tess-muted)]">Agent : {item.agent_id || "—"} · Risque : {item.risk_level || "non précisé"}</p></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-800 dark:bg-amber-400/10 dark:text-amber-200">{item.status}</span></div>{item.reason && <p className="mt-3 text-sm leading-6 text-[var(--tess-muted)]">{item.reason}</p>}<p className="mt-2 font-mono text-[10px] text-[var(--tess-muted)]">Demande {item.approval_id}{item.mission_id ? ` · Mission ${item.mission_id}` : ""}</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => setPendingDecision({ approval: item, approved: true })} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-emerald-700 px-3 text-xs font-semibold text-white hover:bg-emerald-800"><Check className="h-3.5 w-3.5" />Approuver</button><button type="button" onClick={() => setPendingDecision({ approval: item, approved: false })} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-rose-200 px-3 text-xs font-semibold text-rose-700 hover:bg-rose-50 dark:border-rose-400/20 dark:text-rose-200 dark:hover:bg-rose-400/10"><X className="h-3.5 w-3.5" />Rejeter</button></div></article>)}</div> : <div className="tess-hub-card rounded-2xl border border-dashed p-8 text-center"><CircleCheck className="mx-auto h-7 w-7 text-emerald-600" /><p className="mt-2 text-sm font-medium text-[var(--tess-ink)]">Aucune approbation en attente</p><p className="mt-1 text-xs text-[var(--tess-muted)]">Les demandes visibles ici proviennent du runtime connecté.</p></div>}</section>
    {pendingControl && <div role="dialog" aria-modal="true" aria-labelledby="control-confirm-title" className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-md rounded-2xl border border-[var(--tess-line)] bg-white p-5 text-[var(--tess-ink)] shadow-2xl dark:bg-[#171b24]"><h2 id="control-confirm-title" className="text-lg font-semibold">Confirmer : {actionLabel[pendingControl]}</h2><p className="mt-2 text-sm text-[var(--tess-muted)]">Cette commande sera envoyée au runtime et contrôlée par ses permissions.</p>{requiresReason && <label className="mt-4 block text-xs font-semibold">Motif requis<textarea value={controlReason} onChange={event => setControlReason(event.target.value)} minLength={3} maxLength={1000} rows={3} className="mt-1.5 w-full rounded-xl border border-[var(--tess-line)] bg-transparent p-3 text-sm outline-none focus:ring-2 focus:ring-blue-500" placeholder="Décris la raison de cette commande…" /></label>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setPendingControl(null)} className="min-h-10 rounded-xl border border-[var(--tess-line)] px-3 text-xs font-semibold">Annuler</button><button type="button" disabled={Boolean(busy) || (requiresReason && controlReason.trim().length < 3)} onClick={() => void runControl()} className="min-h-10 rounded-xl bg-slate-900 px-3 text-xs font-semibold text-white disabled:opacity-40 dark:bg-white dark:text-slate-900">{busy ? "Envoi…" : "Confirmer"}</button></div></div></div>}
    {pendingDecision && <div role="dialog" aria-modal="true" aria-labelledby="decision-confirm-title" className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-md rounded-2xl border border-[var(--tess-line)] bg-white p-5 text-[var(--tess-ink)] shadow-2xl dark:bg-[#171b24]"><h2 id="decision-confirm-title" className="text-lg font-semibold">{pendingDecision.approved ? "Approuver" : "Rejeter"} cette demande ?</h2><p className="mt-2 text-sm text-[var(--tess-muted)]">{pendingDecision.approval.action || pendingDecision.approval.step_id || "Action opérateur"} · cette décision sera appliquée par le runtime.</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setPendingDecision(null)} className="min-h-10 rounded-xl border border-[var(--tess-line)] px-3 text-xs font-semibold">Annuler</button><button type="button" disabled={Boolean(busy)} onClick={() => void decide()} className={`min-h-10 rounded-xl px-3 text-xs font-semibold text-white disabled:opacity-40 ${pendingDecision.approved ? "bg-emerald-700 hover:bg-emerald-800" : "bg-rose-700 hover:bg-rose-800"}`}>{busy ? "Envoi…" : "Confirmer la décision"}</button></div></div></div>}
  </div></main>;
}
