import { FormEvent, useCallback, useEffect, useState } from "react";
import { Building2, Crosshair, Database, MapPin, RefreshCw, Search, ShieldAlert } from "lucide-react";
import { tessFetch } from "@/lib/tess-client";

type CityPlace = { node_id: string; node_type: string; name: string; local_names?: string[]; latitude?: number | null; longitude?: number | null; attributes?: Record<string, unknown>; sources?: string[]; confidence?: number; city?: string; freshness?: string; retrieved_at?: string };
type CitySnapshot = { city?: string; node_count?: number; edge_count?: number; by_type?: Record<string, number>; knowledge_mode?: string; source_policy?: string; retrieved_at?: string };
const nodeTypes = ["", "place", "quarter", "landmark", "route", "institution", "business", "event"];

export default function TessCityPage() {
  const [snapshot, setSnapshot] = useState<CitySnapshot | null>(null);
  const [query, setQuery] = useState("");
  const [type, setType] = useState("");
  const [results, setResults] = useState<CityPlace[]>([]);
  const [selected, setSelected] = useState<CityPlace | null>(null);
  const [neighbors, setNeighbors] = useState<CityPlace[]>([]);
  const [loading, setLoading] = useState(false);
  const [detailLoading, setDetailLoading] = useState(false);
  const [error, setError] = useState("");
  const [searched, setSearched] = useState(false);
  const loadSnapshot = useCallback(async () => { try { setSnapshot(await tessFetch<CitySnapshot>("/city/snapshot")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Le référentiel local est indisponible."); } }, []);
  useEffect(() => { void loadSnapshot(); }, [loadSnapshot]);
  const search = async (event: FormEvent) => {
    event.preventDefault(); setLoading(true); setError(""); setSearched(true); setSelected(null); setNeighbors([]);
    try { const params = new URLSearchParams({ q: query.trim() || snapshot?.city || "Goma" }); if (type) params.set("node_type", type); setResults(await tessFetch<CityPlace[]>(`/city/places/search?${params.toString()}`)); }
    catch (cause) { setResults([]); setError(cause instanceof Error ? cause.message : "La recherche locale a échoué."); }
    finally { setLoading(false); }
  };
  const openPlace = async (place: CityPlace) => {
    setSelected(place); setDetailLoading(true); setError("");
    try { const [detail, nearby] = await Promise.all([tessFetch<CityPlace>(`/city/places/${encodeURIComponent(place.node_id)}`), tessFetch<CityPlace[]>(`/city/places/${encodeURIComponent(place.node_id)}/neighbors`)]); setSelected(detail); setNeighbors(nearby); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger ce lieu."); }
    finally { setDetailLoading(false); }
  };
  const confidence = (value?: number) => value == null ? "Non précisée" : `${Math.round(value * 100)} %`;

  return <main className="h-full overflow-y-auto bg-[var(--tess-bg)] px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[var(--tess-accent)]">T.E.S.S. · Référentiel local</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[var(--tess-ink)]">Recherche urbaine</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--tess-muted)]">Recherche des lieux et consulte leurs relations dans les données locales disponibles.</p></div><button type="button" onClick={() => void loadSnapshot()} className="inline-flex items-center gap-2 rounded-xl border border-[var(--tess-line)] bg-white px-3 py-2 text-sm font-semibold text-[var(--tess-ink)] transition hover:bg-[var(--tess-mint)] dark:bg-white/[0.04]"><RefreshCw className="h-4 w-4" />Actualiser</button></header>
    <div className="mt-5 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:border-amber-400/20 dark:bg-amber-400/[0.08] dark:text-amber-100"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>{snapshot?.knowledge_mode || "PHASE0_SEED"}.</strong> Référentiel local de {snapshot?.city || "Goma"}, non connecté à une carte ou à une source géographique en temps réel.</p></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><article className="tess-hub-card rounded-2xl border p-4"><div className="flex items-center gap-2 text-xs text-[var(--tess-muted)]"><MapPin className="h-4 w-4" />Nœuds locaux</div><strong className="mt-2 block text-2xl text-[var(--tess-ink)]">{snapshot?.node_count ?? "—"}</strong></article><article className="tess-hub-card rounded-2xl border p-4"><div className="flex items-center gap-2 text-xs text-[var(--tess-muted)]"><Crosshair className="h-4 w-4" />Relations</div><strong className="mt-2 block text-2xl text-[var(--tess-ink)]">{snapshot?.edge_count ?? "—"}</strong></article><article className="tess-hub-card rounded-2xl border p-4"><div className="flex items-center gap-2 text-xs text-[var(--tess-muted)]"><Database className="h-4 w-4" />Provenance</div><strong className="mt-2 block truncate text-sm text-[var(--tess-ink)]">{snapshot?.source_policy || "local_graph_only"}</strong></article></div>
    <form onSubmit={event => void search(event)} className="mt-6 flex flex-col gap-2 rounded-2xl border border-[var(--tess-line)] bg-white p-3 dark:bg-white/[0.04] sm:flex-row"><label className="flex min-h-11 min-w-0 flex-1 items-center gap-2 px-2"><Search className="h-4 w-4 shrink-0 text-[var(--tess-muted)]" /><input value={query} onChange={event => setQuery(event.target.value)} maxLength={200} placeholder={`Rechercher dans ${snapshot?.city || "Goma"}…`} className="min-w-0 flex-1 bg-transparent text-sm text-[var(--tess-ink)] outline-none placeholder:text-[var(--tess-muted)]" /></label><select value={type} onChange={event => setType(event.target.value)} aria-label="Filtrer par type" className="min-h-11 rounded-xl border border-[var(--tess-line)] bg-white px-3 text-sm text-[var(--tess-ink)] dark:bg-[#161b25]"><option value="">Tous les types</option>{nodeTypes.slice(1).map(value => <option key={value} value={value}>{value}</option>)}</select><button type="submit" disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white transition hover:bg-slate-700 disabled:opacity-50 dark:bg-white dark:text-slate-900"><Search className={loading ? "h-4 w-4 animate-pulse" : "h-4 w-4"} />Rechercher</button></form>
    {error && <div role="alert" className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-400/20 dark:bg-rose-500/10 dark:text-rose-200">{error}</div>}
    <div className="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(280px,0.8fr)]"><section aria-label="Résultats de recherche" className="space-y-2">{results.map(place => <button key={place.node_id} type="button" onClick={() => void openPlace(place)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left transition hover:border-blue-300 hover:shadow-sm ${selected?.node_id === place.node_id ? "border-blue-400 bg-blue-50/70 dark:border-blue-400/40 dark:bg-blue-400/[0.08]" : "tess-hub-card"}`}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[var(--tess-mint)] text-[var(--tess-ink)]"><Building2 className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[var(--tess-ink)]">{place.name}</span><span className="mt-0.5 block text-xs text-[var(--tess-muted)]">{place.node_type} · confiance {confidence(place.confidence)}</span></span><span className="text-xs text-[var(--tess-muted)]">{place.city || "Goma"}</span></button>)}{!results.length && <div className="rounded-2xl border border-dashed border-[var(--tess-line)] p-8 text-center text-sm text-[var(--tess-muted)]">{loading ? "Recherche en cours…" : searched ? "Aucun résultat pour cette recherche." : "Lance une recherche pour explorer le référentiel."}</div>}</section>
      <aside className="tess-hub-card h-fit rounded-2xl border p-5"><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[var(--tess-accent)]" /><h2 className="font-semibold text-[var(--tess-ink)]">Détails du lieu</h2></div>{!selected ? <p className="mt-3 text-sm text-[var(--tess-muted)]">Sélectionne un résultat pour afficher ses noms locaux, coordonnées et relations connues.</p> : detailLoading ? <p className="mt-3 text-sm text-[var(--tess-muted)]">Chargement…</p> : <><h3 className="mt-4 text-lg font-semibold text-[var(--tess-ink)]">{selected.name}</h3><p className="mt-1 text-xs text-[var(--tess-muted)]">{selected.node_type} · {selected.node_id}</p>{selected.local_names?.length ? <p className="mt-3 text-sm text-[var(--tess-muted)]">Noms locaux : {selected.local_names.join(", ")}</p> : null}<dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-[var(--tess-muted)]">Confiance</dt><dd className="mt-1 font-semibold text-[var(--tess-ink)]">{confidence(selected.confidence)}</dd></div><div><dt className="text-[var(--tess-muted)]">Source</dt><dd className="mt-1 font-semibold text-[var(--tess-ink)]">{selected.sources?.join(", ") || "Locale"}</dd></div></dl>{selected.latitude != null && selected.longitude != null && <p className="mt-3 font-mono text-xs text-[var(--tess-muted)]">{selected.latitude}, {selected.longitude}</p>}<div className="mt-4 border-t border-[var(--tess-line)] pt-3"><p className="text-xs font-semibold text-[var(--tess-ink)]">Relations connues</p>{neighbors.length ? <ul className="mt-2 space-y-1">{neighbors.map(place => <li key={place.node_id} className="text-xs text-[var(--tess-muted)]">{place.name} · {place.node_type}</li>)}</ul> : <p className="mt-2 text-xs text-[var(--tess-muted)]">Aucune relation disponible.</p>}</div></>}</aside>
    </div>
  </div></main>;
}
